
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author UserNameHere
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        amountTb = new javax.swing.JTextField();
        fromCb = new javax.swing.JComboBox<>();
        toCb = new javax.swing.JComboBox<>();
        convertBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        clearBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Enter Amount");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("From");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("To");

        amountTb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        fromCb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fromCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "CFA", "Pounds", "Euro" }));
        fromCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromCbActionPerformed(evt);
            }
        });

        toCb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        toCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CFA", "USD", "Pounds", "Euro" }));
        toCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toCbActionPerformed(evt);
            }
        });

        convertBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        convertBtn.setText("Convert");
        convertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("FET Currency Converter Java Project");

        clearBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(amountTb)
                            .addComponent(fromCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(toCb, 0, 200, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(clearBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 91, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(convertBtn)
                                .addGap(50, 50, 50))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(99, 99, 99))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(amountTb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(clearBtn))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fromCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(toCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addComponent(convertBtn)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void convertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertBtnActionPerformed
        // TODO add your handling code here:
        
        Double tot;
        Double amount = Double.parseDouble(amountTb.getText());
        
        if(fromCb.getSelectedItem().toString() == "USD" && toCb.getSelectedItem().toString() == "CFA")
        {
           tot = amount * 540;
           JOptionPane.showMessageDialog(this,"Your Amount will be " + tot.toString() + "CFA");
        
        }
        else if(fromCb.getSelectedItem().toString() == "USD" && toCb.getSelectedItem().toString() == "Pounds")
        {
           tot = amount * 0.71;
           JOptionPane.showMessageDialog(this,"Your Amount will be £" + tot.toString());
        
        }
         else if(fromCb.getSelectedItem().toString() == "USD" && toCb.getSelectedItem().toString() == "Euro")
        {
           tot = amount * 0.83;
           JOptionPane.showMessageDialog(this,"Your Amount will be " + tot.toString() + "Euros");
        
        }
         
        
        else if(fromCb.getSelectedItem().toString() == "CFA" && toCb.getSelectedItem().toString() == "USD")
        {
           tot = amount / 540;
           JOptionPane.showMessageDialog(this,"Your Amount will be  $" + tot.toString());
        
        }
        
        else if(fromCb.getSelectedItem().toString() == "CFA" && toCb.getSelectedItem().toString() == "Pounds")
        {
           tot = amount / 762.20;
           JOptionPane.showMessageDialog(this,"Your Amount will be  £" + tot.toString());
        
        }
        else if(fromCb.getSelectedItem().toString() == "CFA" && toCb.getSelectedItem().toString() == "Euro")
        {
           tot = amount / 654.22;
           JOptionPane.showMessageDialog(this,"Your Amount will be " + tot.toString() +"Euros");
        
        }
       
        else if(fromCb.getSelectedItem().toString() == "Pounds" && toCb.getSelectedItem().toString() == "USD")
        {
           tot = amount * 1.41;
           JOptionPane.showMessageDialog(this,"Your Amount will be  $" + tot.toString());
        
        }
        else if(fromCb.getSelectedItem().toString() == "Pounds" && toCb.getSelectedItem().toString() == "CFA")
        {
           tot = amount * 762.20;
           JOptionPane.showMessageDialog(this,"Your Amount will be " + tot.toString() +"CFA");
        
        }
        else if(fromCb.getSelectedItem().toString() == "Pounds" && toCb.getSelectedItem().toString() == "Euro")
        {
           tot = amount * 1.17;
           JOptionPane.showMessageDialog(this,"Your Amount will be " + tot.toString() +"Euros");
        
        }
        
        else if(fromCb.getSelectedItem().toString() == "Euro" && toCb.getSelectedItem().toString() == "CFA")
        {
           tot = amount * 654.22;
           JOptionPane.showMessageDialog(this,"Your Amount will be " + tot.toString() +"CFA");
        
        }
        else if(fromCb.getSelectedItem().toString() == "Euro" && toCb.getSelectedItem().toString() == "Pounds")
        {
           tot = amount * 0.86;
           JOptionPane.showMessageDialog(this,"Your Amount will be  £" + tot.toString());
        
        }
        else if(fromCb.getSelectedItem().toString() == "Euro" && toCb.getSelectedItem().toString() == "USD")
        {
           tot = amount * 1.21;
           JOptionPane.showMessageDialog(this,"Your Amount will be  $" + tot.toString());
        
        }

        
        
        
    }//GEN-LAST:event_convertBtnActionPerformed

    private void fromCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromCbActionPerformed

    private void toCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toCbActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here
        
        amountTb.setText("");
        
    }//GEN-LAST:event_clearBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountTb;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton convertBtn;
    private javax.swing.JComboBox<String> fromCb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> toCb;
    // End of variables declaration//GEN-END:variables
}
